### ISSUE TITLE
화면 깨지시는분 필독

### ISSUE THREAD

**Issue by gusdnd852** [MingusBob/software-community#2]
해당 페이지(jsp파일)에 보시면 

../vendor/~~~
../css/~~~~

이렇게 된거 몇개 있는데 앞에 ../ 이거 지워주면 잘 됩니다.. ㅋㅋㅎㅎ
그때 그때 작업하는사람이 지우는걸로,,,

**Comment by jeongwhanchoi** [comment]
👌
